### ISSUE TITLE
RET_CHECK failure (tensorflow/core/tpu/graph_rewrite/distributed_tpu_rewrite_pass.cc:1768) arg_shape.handle_type != DT_INVALID when using TPU VM

### ISSUE THREAD

**Issue by tgyal** [google-research/simclr#148]
I am trying to run the pretraining on a Google Cloud [TPU VM](https://cloud.google.com/blog/products/compute/introducing-cloud-tpu-vms) in linear eval mode, with TensorFlow nightly (2.6), but I am getting the following error :
`Internal: RET_CHECK failure (tensorflow/core/tpu/graph_rewrite/distrib
uted_tpu_rewrite_pass.cc:1768) arg_shape.handle_type != DT_INVALID`

Note that this issue is only present when using a TPU VM and not when using a standard TPU Node. I have tried using other TensorFlow versions, but this seems to be incompatible with the use of TPU VMs, which is a pretty new feature.

I found that [this older issue](https://github.com/google-research/simclr/issues/53) seems to be the same error, but it wasn't when using a TPU VM and it was apparently solved by upgrading to tf 2.2.

Any help would be greatly appreciated!

Here is the full error for reference:

```
2021-06-21 14:44:16.979264: I tensorflow/core/tpu/graph_rewrite/encapsulate_tpu_computations_pass.cc:263] Subgraph fingerprint:635683022065692940
4
2021-06-21 14:44:18.775531: E tensorflow/compiler/xla/status_macros.cc:56] Internal: RET_CHECK failure (tensorflow/core/tpu/graph_rewrite/distrib
uted_tpu_rewrite_pass.cc:1768) arg_shape.handle_type != DT_INVALID  input edge: [id=4870 Func/while/body/_1/input/_968:0 -> cluster_while_body_34
193:473]
*** Begin stack trace ***
        tensorflow::CurrentStackTrace[abi:cxx11]()

        xla::status_macros::MakeErrorStream::Impl::GetStatus()
        tensorflow::DistributedTPURewritePass::GetArgAndRetvalShapes(std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<tensorflow::InferredShape, std::allocator<tensorflow::InferredShape> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<tensorflow::InferredShape, std::allocator<tensorflow::InferredShape> > > > > const&, tensorflow::Node const&, tensorflow::DistributedTPURewritePass::ParameterInfo const&, std::vector<tensorflow::InferredShape, std::allocator<tensorflow::InferredShape> >*, std::vector<tensorflow::InferredShape, std::allocator<tensorflow::InferredShape> >*)
        tensorflow::DistributedTPURewritePass::RewriteTPUReplicateNode(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, tensorflow::DeviceSet const&, tensorflow::Node*, tensorflow::FunctionLibraryDefinition*, tensorflow::FunctionLibraryRuntime*, tensorflow::Node*, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<tensorflow::Node*, std::allocator<tensorflow::Node*> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<tensorflow::Node*, std::allocator<tensorflow::Node*> > > > > const&, std::vector<tensorflow::Node*, std::allocator<tensorflow::Node*> > const&, absl::lts_20210324::node_hash_map<tensorflow::Node*, std::vector<tensorflow::Node*, std::allocator<tensorflow::Node*> >, absl::lts_20210324::container_internal::HashEq<tensorflow::Node*, void>::Hash, absl::lts_20210324::container_internal::HashEq<tensorflow::Node*, void>::Eq, std::allocator<std::pair<tensorflow::Node* const, std::vector<tensorflow::Node*, std::allocator<tensorflow::Node*> > > > >*, tensorflow::Graph*, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<tensorflow::InferredShape, std::allocator<tensorflow::InferredShape> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<tensorflow::InferredShape, std::allocator<tensorflow::InferredShape> > > > > const&, absl::lts_20210324::flat_hash_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::allocator<std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >, absl::lts_20210324::container_internal::StringHash, absl::lts_20210324::container_internal::StringHashEq::Eq, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::allocator<std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > > > >*, long)
        tensorflow::DistributedTPURewritePass::Run(tensorflow::GraphOptimizationPassOptions const&)
        tensorflow::OptimizationPassRegistry::RunGrouping(tensorflow::OptimizationPassRegistry::Grouping, tensorflow::GraphOptimizationPassOptions const&)
        tensorflow::ProcessFunctionLibraryRuntime::InstantiateMultiDevice(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, tensorflow::AttrSlice, tensorflow::FunctionLibraryRuntime::InstantiateOptions const&, unsigned long*)
        tensorflow::ProcessFunctionLibraryRuntime::Instantiate(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, tensorflow::AttrSlice, tensorflow::FunctionLibraryRuntime::InstantiateOptions const&, unsigned long*)
        tensorflow::KernelAndDeviceFunc::InstantiateFunc(bool, tensorflow::NodeDef const&, tensorflow::GraphCollector*)
        tensorflow::KernelAndDeviceFunc::Init(bool, tensorflow::NodeDef const&, tensorflow::GraphCollector*)


        tensorflow::EagerExecute(tensorflow::EagerOperation*, tensorflow::TensorHandle**, int*)
        tensorflow::EagerOperation::Execute(absl::lts_20210324::Span<tensorflow::AbstractTensorHandle*>, int*)
        tensorflow::CustomDeviceOpHandler::Execute(tensorflow::ImmediateExecutionOperation*, tensorflow::ImmediateExecutionTensorHandle**, int*)
        TFE_Execute
        TFE_Py_ExecuteCancelable(TFE_Context*, char const*, char const*, absl::lts_20210324::InlinedVector<TFE_TensorHandle*, 4ul, std::allocator<TFE_TensorHandle*> >*, _object*, TFE_CancellationManager*, absl::lts_20210324::InlinedVector<TFE_TensorHandle*, 2ul, std::allocator<TFE_TensorHandle*> >*, TF_Status*)

        PyCFunction_Call
        _PyObject_MakeTpCall
        _PyEval_EvalFrameDefault
        _PyEval_EvalCodeWithName
        _PyFunction_Vectorcall
        _PyEval_EvalFrameDefault
        _PyEval_EvalCodeWithName

        _PyEval_EvalFrameDefault
        _PyEval_EvalCodeWithName

        _PyEval_EvalFrameDefault
        _PyEval_EvalCodeWithName
        _PyFunction_Vectorcall

        PyObject_Call
        _PyEval_EvalFrameDefault
        _PyEval_EvalCodeWithName
        _PyFunction_Vectorcall

        PyObject_Call
        _PyEval_EvalFrameDefault
        _PyEval_EvalCodeWithName
        _PyFunction_Vectorcall

        _PyObject_MakeTpCall
        _PyEval_EvalFrameDefault
        _PyEval_EvalCodeWithName
        _PyFunction_Vectorcall
        _PyEval_EvalFrameDefault
        _PyFunction_Vectorcall
        _PyEval_EvalFrameDefault
        _PyEval_EvalCodeWithName
        _PyFunction_Vectorcall
        _PyEval_EvalFrameDefault
        _PyEval_EvalCodeWithName
        PyEval_EvalCode


        PyRun_FileExFlags
        PyRun_SimpleFileExFlags
        Py_RunMain
        Py_BytesMain
        __libc_start_main
        _start
*** End stack trace ***

Traceback (most recent call last):
  File "run.py", line 718, in <module>
    app.run(main)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "run.py", line 694, in main
    train_multiple_steps(iterator)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/def_function.py", line 885, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/def_function.py", line 946, in _call
    return self._stateless_fn(*args, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 3032, in __call__
    return graph_function._call_flat(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 1956, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 591, in call
    outputs = execute.execute(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InternalError: RET_CHECK failure (tensorflow/core/tpu/graph_rewrite/distributed_tpu_rewrite_pass.cc:1768) arg_shape.handle_type != DT_INVALID  input edge: [id=4870 Func/while/body/_1/input/_968:0 -> cluster_while_body_34193:473] [Op:__inference_train_multiple_steps_56952]
```

**Comment by chentingpc** [comment]
It's not obvious to me what the error is, are you sure the TPU is available and used? If you're not using TPU, setting `use_tpu=False` may help.

**Comment by tgyal** [comment]
After some digging I found that this issue was related to the tf summaries. I looked around the SimCLR code and luckily I found how to solve this issue. 

For anyone trying to run SimCLR on a cloud TPU VM with summaries enabled, what solved the RET_CHECK failure for me was to move the training steps outside the of the `with summary_writer.as_default()` in the main `run.py` file starting at line 640, as shown below.

```
while cur_step < train_steps:
  train_multiple_steps(iterator)
  cur_step = global_step.numpy()
  checkpoint_manager.save(cur_step)
  logging.info('Completed: %d / %d steps', cur_step, train_steps)
  
  # Calls to tf.summary.xyz lookup the summary writer resource which is
  # set by the summary writer's context manager.
  with summary_writer.as_default():
    metrics.log_and_write_metrics_to_summary(all_metrics, cur_step)
    tf.summary.scalar(
        'learning_rate',
        learning_rate(tf.cast(global_step, dtype=tf.float32)),
        global_step)
    summary_writer.flush()
```
