### ISSUE TITLE
Error about tf2

### ISSUE THREAD

**Issue by lucasliunju** [google-research/simclr#160]
I'm running the code of tf2. It occurs this error:

I0811 08:52:13.466977 139682978502464 logging_logger.py:34] Constructing tf.data.Dataset imagenet2012 for split tra
in, from gs://lucas_2021/imagenet2012/manual/imagenet2012/5.1.0
Traceback (most recent call last):
  File "run.py", line 671, in <module>
    app.run(main)
  File "/home/supercomputer_ai/.local/lib/python3.7/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/supercomputer_ai/.local/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "run.py", line 526, in main
    True, strategy, topology)
  File "/home/supercomputer_ai/simclr/tf2/data.py", line 98, in build_distributed_dataset
    return strategy.distribute_datasets_from_function(input_fn)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/distribute_lib.py", line 1160, in distr
ibute_datasets_from_function
2021-08-11 08:52:13.563354: W ./tensorflow/core/distributed_runtime/eager/destroy_tensor_handle_node.h:57] Ignoring
 an error encountered when deleting remote tensors handles: Invalid argument: Unable to find the relevant tensor re
mote_handle: Op ID: 338, Output num: 0
Additional GRPC error information from remote target /job:worker/replica:0/task:0:
:{"created":"@1628671933.560038856","description":"Error received from peer ipv4:10.240.1.19:8470","file":"external
/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Unable to find the relevant te
nsor remote_handle: Op ID: 338, Output num: 0","grpc_status":3}
    dataset_fn, options)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/tpu_strategy.py", line 975, in _distrib
ute_datasets_from_function
    options=options)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/input_lib.py", line 168, in get_distrib
uted_datasets_from_function
    input_contexts, dataset_fn, options)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/input_lib.py", line 1566, in __init__
    input_contexts, self._input_workers, dataset_fn))
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/input_lib.py", line 2301, in _create_da
tasets_from_function_with_input_context
    dataset = dataset_fn(ctx)
File "/home/supercomputer_ai/simclr/tf2/data.py", line 75, in _input_fn
    input_context=input_context))
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_datasets/core/logging/__init__.py", line 66, in decorator
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_datasets/core/dataset_builder.py", line 584, in as_dataset
    datasets = utils.map_nested(build_single_dataset, split, map_tuple=True)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_datasets/core/utils/py_utils.py", line 185, in map_nested
    return function(data_struct)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_datasets/core/dataset_builder.py", line 606, in _build_single_dataset
    read_config=read_config,
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_datasets/core/dataset_builder.py", line 958, in _as_dataset
    shuffle_files=shuffle_files,
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_datasets/core/tfrecords_reader.py", line 362, in read
    return tf.nest.map_structure(_read_instruction_to_ds, instructions)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/nest.py", line 867, in map_structure
    structure[0], [func(*x) for x in entries],
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/nest.py", line 867, in <listcomp>
    structure[0], [func(*x) for x in entries],
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_datasets/core/tfrecords_reader.py", line 359, in _read_instruction_to_ds
    decode_fn=decode_fn,
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_datasets/core/tfrecords_reader.py", line 401, in read_files
    file_format=self._file_format,
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_datasets/core/tfrecords_reader.py", line 264, in _read_files
    index=read_config.input_context.input_pipeline_id,
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 1588, in shard
    return ShardDataset(self, num_shards, index)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 4082, in __init__
    **self._flat_structure)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/gen_dataset_ops.py", line 6104, in shard_dataset
    _ops.raise_from_not_ok_status(e, name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 6897, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.UnimplementedError: File system scheme '[local]' not implemented (file: 'model')
        Encountered when executing an operation using EagerExecutor. This error cancels all future operations and poisons their output tensors. [Op:ShardDataset]

Could you give me some advice on that.

**Comment by chentingpc** [comment]
I'm not familiar with with issue, but it looks like it's not able to load data from gcs. Looking at [tfds builder api](https://www.tensorflow.org/datasets/api_docs/python/tfds/builder), you may want to set `try_gcs=True`?

**Comment by lucasliunju** [comment]
Thanks a lot. This issue is solved!
